# Plugin configuration for FastCraft

$a0: '# If the language specified does not exist, a new language file will'
$a1: '# be added to the lang folder in the FastCraft plugin directory.'
$a2: '# Available languages:'
$a3: '# English (EN), Deutsch (DE), Español (ES)'
$a4: '# Русский язык (RU), Čeština (CS),'
$a5: '# Türkçe (TR), Nederlands (NL),'
$a6: '# 中文 (ZH-CN), 台語 (ZH-TW),'
$a7: '# Tiếng Việt (VI), Polskie (PL)'
language: EN

$b0: ''
$b1: '# Whether FastCraft is enabled for players by default.'
default-enabled: true

$c0: ''
$c1: '# Toolbar settings'
$c2: '# gap:              Hide/show the gap above the toolbar.'
$c3: '# layout:           Position of buttons in the toolbar, or -1 to hide.'
$c4: '# multiplier-order: The multipliers used by the multiplier button.'
toolbar:
  gap: true
  layout:
    page-prev: 0
    page-next: 8
    multiplier: 3
    workbench: 4
    refresh: 5
  multiplier-order: 1, 2, 3, 4, 6, 8, 12, 16, 24, 32, 48, 64

$e0: ''
$e1: '# If true, extra messages will be written to the console.'
debug: false
